import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import HomeHero from '../components/HomeHero'
import Nav from '../components/Nav'
import Offer from '../components/Offer'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={`min-h-screen bg-background text-text-secondary items-center justify-center`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Offer/>

      <Nav/>
      
      <HomeHero/>
      
    </div>
  )
}

export default Home
