import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import HomeHero from '../components/HomeHero'
import Nav from '../components/Nav'
import Offer from '../components/Offer'

const Home: NextPage = () => {
  return (
    <div className={`min-h-screen bg-background text-text-secondary items-center justify-center`}>
      <Head>
        <title>Limbo Funnles</title>
        <meta name="description" content="Generated by Limbo Funnles" />
        <link rel="icon" type="image/png" href="/favicon.png" />
      </Head>

      <Offer/>

      <Nav/>
      
      <HomeHero/>
      
    </div>
  )
}

export default Home
